# Generated by Django 4.1.1 on 2022-09-18 08:50

import cloudinary.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', django_resized.forms.ResizedImageField(crop=['top', 'left', 'right'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[576, 256], upload_to='images/books')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pdf', cloudinary.models.CloudinaryField(max_length=255)),
            ],
            options={
                'verbose_name_plural': "PDF's",
            },
        ),
    ]
