# Generated by Django 4.1.1 on 2022-09-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='description',
        ),
    ]
